baseURL                     = "http://media.phlow.de/test/"
languageCode                = "de-DE"
defaultContentLanguage      = "de"
title                       = "Phlow Seminare"
theme                       = "amplified"
copyright                   = "Alle Rechte vorbehalten"

enableRobotsTXT = true
canonifyURLs = true

# {{ .Site.GoogleAnalytics }}
# googleAnalytics             = ""


# Markdown
# https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Default JPEG quality setting. Default is 75.
quality = 80

[author]
    name                  = "Moritz mo. Sauer"
    publisher             = "Phlow"

[permalinks]
  seminare = "/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"

# Verhindern <meta name="generator" content="Hugo 0.18" />
disableHugoGeneratorInject  = true

[params]
    slogan                  = "Phlow Seminare – WordPress, Social Media, SEO & Journalismus"
    description             = "Seit mehr als 10 Jahren trainieren wir unsere Kunden in den Bereichen WordPress, Journalismus, Social Media, Internet Marketing und Webdesign."
    adsensePublisher        = ""
  # Wichtig für SCHEMA.ORG
  [params.publisher]
    name = "Phlow"

    # Wichtig für SCHEMA.ORG
    [params.publisher.logo]
      # https://developers.google.com/search/docs/data-types/article#logo-guidelines
      # The logo should fit in a 60x600px rectangle, and either be exactly 60px high (preferred), or exactly 600px wide. 
      url = "/assets/img/amp-logo-schema-small-150-60.png"
      width = 150
      height = 60

  # Wichtig für SCHEMA.ORG
  [params.logo]
    url = "/assets/img/amp-logo-schema-small-150-60.png"
    width = 150
    height = 60

  # Wichtig für SCHEMA.ORG
  [params.image]
    # The URL to an image that is representative of the article or AMP story.
    # Images should be at least 1200 pixels wide.
    # For best results, provide multiple high-resolution images (minimum of 800,000 pixels when multiplying width and height) with the following aspect ratios: 16x9, 4x3, and 1x1.
    url = "/assets/img/amp-banner-homepage-1600x900.jpg"
    width = 1600
    height = 900

  [params.socialmedia]
    youtube   = "PhlowMedia"
    twitter   = "phlow"
    instagram = "phlowmedia"
    facebook  = "phlow.media"
    github    = "phlow"
    # soundcloud: phlow
    # rss: # Full URL needed
